# Generated by Django 5.0.9 on 2026-08-27 11:30

import apps.referrals.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0002_initial'),
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference_code', models.CharField(max_length=20, unique=True)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='ROUTINE', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ROUTED', 'Routed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=20)),
                ('reason_for_referral', models.TextField()),
                ('clinical_summary', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('routed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_referrals', to='hospitals.specialist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_created', to=settings.AUTH_USER_MODEL)),
                ('destination_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='hospitals.department')),
                ('destination_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals_received', to='hospitals.hospital')),
                ('originating_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_originated', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='patients.patient')),
                ('referring_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_created', to='hospitals.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.referrals.models.referral_document_upload_path)),
                ('document_type', models.CharField(choices=[('LAB_RESULT', 'Lab Result'), ('IMAGING', 'Imaging'), ('REFERRAL_LETTER', 'Referral Letter'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='referrals.referral')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('GENERAL', 'General'), ('DIAGNOSIS', 'Diagnosis'), ('TREATMENT_PLAN', 'Treatment Plan'), ('OUTCOME', 'Outcome')], default='GENERAL', max_length=20)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='referrals.referral')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='referrals.referral')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_assignments', to='hospitals.specialist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='referrals.referral')),
            ],
            options={
                'verbose_name_plural': 'Referral status histories',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status', 'priority'], name='referrals_r_status_6da231_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['patient', 'status'], name='referrals_r_patient_fc132b_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['originating_hospital', 'status'], name='referrals_r_origina_6667b2_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['destination_hospital', 'status'], name='referrals_r_destina_c5f448_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['assigned_specialist', 'status'], name='referrals_r_assigne_56c775_idx'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(check=models.Q(('priority__in', ['ROUTINE', 'URGENT', 'EMERGENCY'])), name='referral_priority_valid'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['referral', 'document_type'], name='referrals_d_referra_1b1183_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['referral', 'note_type'], name='referrals_c_referra_080250_idx'),
        ),
        migrations.AddIndex(
            model_name='referralassignment',
            index=models.Index(fields=['referral', 'status'], name='referrals_r_referra_101fee_idx'),
        ),
        migrations.AddIndex(
            model_name='referralassignment',
            index=models.Index(fields=['specialist', 'status'], name='referrals_r_special_831d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='referralstatushistory',
            index=models.Index(fields=['referral', 'created_at'], name='referrals_r_referra_fbd6a0_idx'),
        ),
    ]
