# Generated by Django 5.0.9 on 2026-08-27 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('hospitals', '0002_initial'),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='referrals.referral'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='hospitals.specialist'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['specialist', 'scheduled_start'], name='appointment_special_f955ae_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'scheduled_start'], name='appointment_status_fcb044_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['referral', 'status'], name='appointment_referra_98b087_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('scheduled_end__gt', models.F('scheduled_start'))), name='appointment_end_after_start'),
        ),
    ]
