# Generated by Django 5.0.9 on 2026-08-27 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_active', 'city'], name='hospitals_h_is_acti_1a4ad1_idx'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialists', to='hospitals.department'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialists', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['hospital', 'is_active'], name='hospitals_d_hospita_57ce82_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['hospital', 'is_active'], name='hospitals_d_hospita_03c50b_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('hospital', 'code'), name='unique_department_code_per_hospital'),
        ),
        migrations.AddIndex(
            model_name='specialist',
            index=models.Index(fields=['hospital', 'department', 'is_accepting_referrals'], name='hospitals_s_hospita_4f495f_idx'),
        ),
    ]
