# Generated by Django 5.0.9 on 2026-08-27 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REFERRAL_ROUTED', 'Referral Routed'), ('REFERRAL_ACCEPTED', 'Referral Accepted'), ('REFERRAL_REJECTED', 'Referral Rejected'), ('REFERRAL_COMPLETED', 'Referral Completed'), ('REFERRAL_CANCELLED', 'Referral Cancelled'), ('REFERRAL_EXPIRED', 'Referral Expired'), ('APPOINTMENT_SCHEDULED', 'Appointment Scheduled'), ('APPOINTMENT_REMINDER', 'Appointment Reminder')], max_length=30)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email')], default='IN_APP', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
