# Generated by Django 5.0.9 on 2026-08-27 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='referrals.referral'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['referral', 'notification_type'], name='notificatio_referra_f05ee3_idx'),
        ),
    ]
